routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('admin.content.kategori.kategori');
});

Route::resource('/kategori', 'Kategori_controller');
Route::get('/source/kategori', 'Kategori_controller@datatables')->name('source.kategori');

app/Gambar.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class gambar extends Model
{
    protected $table = 'gambars';
    protected $primaryKey = 'id_gambar';


    public function kategori()
    {
        return $this->hasOne('App\Kategori', 'id_kategori', 'parent_id_kategori');
    }

    public function users()
    {
        return $this->hasOne('App\User', 'id', 'parent_id_user');
    
    }
    public function porto()
    {
        return $this->hasOne('App\Portofolio', 'id_porto', 'parent_id_porto');
    }


}

app/Kategori.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class kategori extends Model
{
    protected $table = 'kategoris';
    protected $primaryKey = 'id_kategori';


    public function gambar()
    {
        return $this->hasMany('App\Gambar', 'parent_id_kategori', 'id_kategori');
    }

    public function users()
    {
        return $this->hasOne('App\User', 'id', 'id_user');
    
    }
}

app/Portofolio.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class portofolio extends Model
{
    protected $table = 'portofolios';
    protected $primaryKey = 'id_porto';


    public function gambar()
    {
        return $this->hasMany('App\Gambar', 'parent_id_porto', 'id_porto');
    }

    public function users()
    {
        return $this->hasOne('App\User', 'id', 'perent_id_user');
    }
}

app/Team.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class team extends Model
{
    protected $table = 'teams';
    protected $primaryKey = 'id_team';


    public function users()
    {
        return $this->hasOne('App\User', 'id', 'id_team');
    
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/Kategori_controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Yajra\DataTables\Facades\DataTables;
use Illuminate\Support\Facades\DB;
use App\kategori;
class Kategori_controller extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {               
        return view('admin.content.kategori.kategori');

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        return $request->all();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function datatables()
    {
        $query = kategori::query()->latest('updated_at');
       
        return DataTables::eloquent($query)
        ->addIndexColumn()       
        ->toJson();
        return view('admin.content.kategori.kategori');
    }
}

app/Http/Controllers/PortofolioController.php
<?php

namespace App\Http\Controllers;

use App\portofolio;
use Illuminate\Http\Request;

class PortofolioController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\portofolio  $portofolio
     * @return \Illuminate\Http\Response
     */
    public function show(portofolio $portofolio)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\portofolio  $portofolio
     * @return \Illuminate\Http\Response
     */
    public function edit(portofolio $portofolio)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\portofolio  $portofolio
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, portofolio $portofolio)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\portofolio  $portofolio
     * @return \Illuminate\Http\Response
     */
    public function destroy(portofolio $portofolio)
    {
        //
    }
}

resources/views/admin/content/kategori/kategori.blade.php
@extends('admin.parts.main')

@section('content')
<div class="row">
    <div class="col-lg-12">
        <h1>Portofoliso <small>Enter Your Data</small></h1>
        <ol class="breadcrumb">
            <li><a href="index.html"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            <li class="active"><i class="fa fa-edit"></i> Portofolio</li>
            <button type="button" class="btn btn-default" data-toggle="modal" data-target="#modal-default">
                Launch Default Modal
            </button>
        </ol>

    </div>
</div><!-- /.row -->

<div class="row">
    <div class="col-lg-12">
        <table class="table table-bordered" id="table_kategori">
            <thead>
                <tr>
                    <th>No</th>
                    <th>Name</th>
                </tr>
            </thead>
        </table>
    </div>
</div><!-- /.row -->

<div class="modal fade" id="modal-default" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Default Modal</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <p>One fine body…</p>
            </div>
            <div class="modal-footer justify-content-between">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal-content -->
@endsection

@push('css')
{{-- <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet"> --}}
<link rel="stylesheet" href="//cdn.datatables.net/1.10.7/css/jquery.dataTables.min.css">
@endpush

@push('js')
<!-- DataTables -->
<script src="//cdn.datatables.net/1.10.7/js/jquery.dataTables.min.js"></script>
<!-- Bootstrap JavaScript -->
<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
@endpush

@push('script')
<script>
    const $table = $("#table_kategori").DataTable({
        responsive: true,
        autoWidth: false,
        processing: true,
        serverSide: true,
        responsive: true,
        ajax: {
            url: '{!! route("source.kategori") !!}',
            dataSrc: 'data'
        },
        language: {
            paginate: {
                previous: "<i class='fa fa-chevron-left'></i>",
                next: "<i class='fa fa-chevron-right'></i>",
            }
        },
        columns: [
            // {data: 'DT_RowIndex', name: 'DT_RowIndex',width:"2%", orderable : false, searchable : false, className: 'text-center'},
            {
                data: 'DT_RowIndex',
                name: 'DT_RowIndex',
                orderable: false
            },
            {
                data: 'nama_kategori',
                name: 'nama_kategori'
            },
            // {data: 'action', name: 'action', searchable : false, orderable : false, className: 'text-center'}
        ],
        columnDefs: [{
            width: "10%",
            targets: 0
        }],
        lengthMenu: [
            [5, 10, 25, 50],
            [5, 10, 25, 50]
        ],
        search: {
            "regex": true
        }
    });

    function store(val) {
        var data = $('#form_data').serialize();

        $.ajax({
            type: 'post',
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            },
            url: '{!!route("kategori.store")!!}',
            dataType: 'json',
            data: data,
            async: true,
            beforeSend: function() {
                $('#submit').prop('disabled', true);
            },
            success: function(data) {
                $('#modal-w').modal('toggle');
                $table.ajax.reload()
            },
            error: function(data) {
                $('#submit').prop('disabled', false);
                if (data.status === 422) {
                    var errors = $.parseJSON(data.responseText);
                    $.each(errors['errors'], function(index, value) {
                        $('#form_create').Toasts('create', {
                            title: 'Error Input' + index,
                            autohide: true,
                            class: 'bg-danger',
                            delay: 2500,
                            body: value

                        })
                    });

                }
            },
        });
    }
</script>
@endpush

resources/views/admin/content/portofolio/porto_form_input.blade.php
@extends('admin.parts.main')

@section('content')
<div class="row">
    <div class="col-lg-12">
        <h1>Portofoliso <small>Enter Your Data</small></h1>
        <ol class="breadcrumb">
            <li><a href="index.html"><i class="fa fa-dashboard"></i> Dashboard</a></li>
            <li class="active"><i class="fa fa-edit"></i> Portofolio</li>
        </ol>

    </div>
</div><!-- /.row -->

<div class="row">
    <div class="col-lg-6">
        <button type="button" class="btn btn-default" data-toggle="modal" data-target="#modal-default">
            add Image
        </button>
    </div>
</div><!-- /.row -->
<form role="form" action="">
    <div class="modal fade" id="modal-default">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span></button>
                    <h4 class="modal-title">Default Modal</h4>
                </div>
                <div class="modal-body">

                    <div class="form-group">
                        <label>Kategori</label>
                        <select class="form-control">
                            <option>option 1</option>
                            <option>option 2</option>
                            <option>option 3</option>
                            <option>option 4</option>
                            <option>option 5</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label>File input</label>
                        <input type="file">

                    </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-default">Submit Button</button>
                    <button type="reset" class="btn btn-default">Reset Button</button>
                </div>
            </div>
</form>
<!-- /.modal-content -->
</div>
<!-- /.modal-dialog -->
</div>
@endsection


@push('style')
<link rel="stylesheet" href="{{asset('assets/css/dropzone.css')}}">
@endpush
@push('js')
<script src="{{asset('assets/js/dropzone.js')}}"></script>
@endpush
@push('script')
<script>
    Dropzone.options.dropzone =
    {
        maxFilesize: 2,
        maxFiles: 1,
        init: function ()  {
            this.on("error", function (file, message) {
                $(document).Toasts('create', {                 
                    title: 'Error',
                    autohide: true,
                    class: 'bg-danger',
                    delay: 2500,
                    body: message
            
                });
                this.removeFile(file);
            }); 
        },
        acceptedFiles: ".jpeg,.jpg,.png,.gif",
        addRemoveLinks: true,
        timeout: 5000,
        success: function(file, response) 
        {
            console.log(response);
        },
        error: function(file, response)
        {
            return false;
        }
    };
</script>
@endpush

resources/views/admin/parts/_css.blade.php
<!-- Bootstrap core CSS -->
<link href="{{asset('assets/css/bootstrap.css')}}" rel="stylesheet">

<!-- Add custom CSS here -->
<link href="{{asset('assets/css/sb-admin.css')}}" rel="stylesheet">
<link rel="stylesheet" href="{{asset('assets/font-awesome/css/font-awesome.min.css')}}">
<!-- Page Specific CSS -->
<!-- <link rel="stylesheet" href="http://cdn.oesmith.co.uk/morris-0.4.3.min.css"> -->

@stack('css')
@stack('style')

resources/views/admin/parts/_js.blade.php
<!-- JavaScript -->
<script src="{{asset('assets/js/jquery-1.10.2.js')}}"></script>
<script src="{{asset('assets/js/bootstrap.js')}}"></script>

<!-- Page Specific Plugins -->
<script src="//cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
<!-- <script src="http://cdn.oesmith.co.uk/morris-0.4.3.min.js"></script> -->
<script src="{{asset('assets/js/morris/chart-data-morris.js')}}"></script>
<script src="{{asset('assets/js/tablesorter/jquery.tablesorter.js')}}"></script>
<script src="{{asset('assets/js/tablesorter/tables.js')}}"></script>

@stack('js')

@stack('script')

resources/views/admin/parts/header.blade.php
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="">
<meta name="author" content="">

<title>Halaman Admin</title>

resources/views/admin/parts/main.blade.php
<!DOCTYPE html>
<html lang="en">

<head>

    @include('admin.parts.header')

    @include('admin.parts._css')

</head>

<body>

    <div id="wrapper">

        @include('admin.parts.side')

        <div id="page-wrapper">

            @yield('content')

        </div>
    </div>
    </div>
    </div><!-- /.row -->

    </div><!-- /#page-wrapper -->

    </div><!-- /#wrapper -->

    @include('admin.parts._js')


</body>

</html>

resources/views/admin/parts/side.blade.php
  <!-- Sidebar -->
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="index.html">Halaman Admin</a>
      </div>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse navbar-ex1-collapse">
          <ul class="nav navbar-nav side-nav">
              <li class="active"><a href="index.html"><i class="fa fa-dashboard"></i> Dashboard</a></li>

              <li class="active"><a href="portofolio.html"><i class="fa fa-edit"></i> Portofolio</a></li>
              <li class="active"><a href="foto.html"><i class="fa fa-edit"></i> Gallery</a></li>

          </ul>
          </li>
          </ul>

          <ul class="nav navbar-nav navbar-right navbar-user">
              <li class="dropdown messages-dropdown">

              <li class="dropdown user-dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> Admin <b class="caret"></b></a>
                  <ul class="dropdown-menu">

                      <li><a href="#"><i class="fa fa-gear"></i> Settings</a></li>
                      <li class="divider"></li>
                      <li><a href="#"><i class="fa fa-power-off"></i> Log Out</a></li>
                  </ul>
              </li>
          </ul>
      </div><!-- /.navbar-collapse -->
  </nav>